Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
    path('comments/<int:pizza_id>/',views.comments, name='comments')
]

urlpatterns += staticfiles_urlpatterns()

pizzas/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='img',blank=True,null=True)

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()

    def __str__(self):
        return self.topping_name

class Comments(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms
from .models import Comments

class Comment(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Pizza, Topping, Comments
from .forms import Comment
from django.urls import reverse
# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}

    return render(request,'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    comments = pizza.comments_set.all().order_by('-date_added')
    picture = Pizza.picture
    context = {'pizza':pizza,'toppings':toppings,'comments':comments}

    return render(request, 'pizzas/pizza.html', context)

def comments(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = Comment()
    else:
        form = Comment(data=request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.pizza = pizza
            comments.save()

            return HttpResponseRedirect(reverse('pizzas:pizza',args=[pizza_id]))

    comments = Comments.objects.all()
    context = {'pizza': pizza, 'form': form,'comments':comments}
    return render(request, 'pizzas/comments.html', context)

pizzas/templates/pizzas/base.html
<p> 
    <a href="{% url 'pizzas:index' %}">Home Page</a>
    <a href="{% url 'pizzas:pizzas' %}">Available Pizzas</a>
</p>

{% block content %}


{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}

{% block content %}


<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }} </a></p>

<p>Enter Comment:</p>
<form action="{% url 'pizzas:comments' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name ='submit'>add entry</button>
</form>



{% endblock content %}

pizzas/templates/pizzas/index.html
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body style="background-color: #ADD8E6;">
    <h1 style = "color: red; font-size: 60px; border: 3px; border-style: solid; border-color: black; text-align: center;"> Welcome to James Pizza</h1>

<p style = "font-weight: bold; font-size: 30px; text-align: center;">
    View our selection of amazing pizzas!
</p>    

<p style = "font-size: 20px; text-align: center;">
    <a href="{% url 'pizzas:pizzas' %}">Available Pizzas</a>
</p>

</body>
{% endblock content %}
    

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> 
    Pizza: {{ pizza }}
</p>

<ul>
    {% for t in toppings %}
    <li>
        <p> {{ t.topping_name }}</p>
    </li>
    {% empty %}
    <li> There are no toppings for this pizza yet. </li>
    {% endfor %}
</ul>

<p>
    <img src="{{ pizza.picture.url }}">
</p>

<p>Comments</p>
<ul>
    {% for c in comments %}
    <li>
        <p> {{ c.text }}</p>
    </li>
    {% empty %}
    <li> There are no comments for this pizza yet. </li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'pizzas:comments' pizza.id %}">Submit a Comment!</a>
</p>


{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
<body style="background-color: #ADD8E6;">
<p style="font-size: 30px; font-weight: bold;"> Pizzas </p>

<ul> 
    {% for t in pizzas %}

    <li> 
    <a href="{% url 'pizzas:pizza' t.id %}">{{ t }} </li></a>
    {% empty %}
    <li> No pizzas have been added yet.</li>
    {% endfor %}
</ul>

</body>
{% endblock content %}